steps:
  - name: gcr.io/cloud-builders/git
    args:
      - submodule
      - update
      - "--init"
      - "--recursive"
  - name: "node:18-alpine"
    args:
      - install
      - run
      - start
      - "--"
    entrypoint: npm
  - name: gcr.io/cloud-builders/gcloud
    args:
      - app
      - deploy
      - app-prod.yaml
      - "--version=prod"
timeout: 1600s