FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ENV DB_URL=${_DB_URL}
ENV DB_NAME=${_DB_NAME}
ENV EMAIL_SERVICE=${_EMAIL_SERVICE}
ENV EMAIL_USER=${_EMAIL_USER}
ENV EMAIL_PASSWORD=${_EMAIL_PASSWORD}
ENV SERVER_URL=${_SERVER_URL}
ENV STRIPE_KEY=${_STRIPE_KEY}
ENV BUCKET_NAME=${_BUCKET_NAME}
ENV SUPER_ADMIN_IP=${_SUPER_ADMIN_IP}
ENV PGHOST=${_PGHOST}
ENV PGUSER=${_PGUSER}
ENV PGDATABASE=${_PGDATABASE}
ENV PGPASSWORD=${_PGPASSWORD}
ENV PGPORT=${_PGPORT}
ENV MAILCHIMP_KEY=${_MAILCHIMP_KEY}
ENV MAILCHIMP_SERVER=${_MAILCHIMP_SERVER}
ENV MAILCHIMP_FLIPNBID_LIST_ID=${_MAILCHIMP_FLIPNBID_LIST_ID}

EXPOSE 8080

CMD ["npm", "start"]
